#!/usr/bin/env python3
"""Real PTY frontend tests plus deterministic interpretation of colour output.

The models cover both modern colour switches and pre-0.71 PuTTY SGR
parsing, including unsupported RGB operands being treated as attributes. It is not Windows PuTTY and does not establish
pixel-level Windows font or display behaviour.
"""
from __future__ import annotations
import fcntl
import json
import os
from pathlib import Path
import pty
import re
import select
import signal
import socket
import struct
import subprocess
import sys
import tempfile
import termios
import time
import unittest
import unicodedata

BINARY = str(Path(sys.argv.pop(1)).resolve())
ROOT = Path(__file__).resolve().parents[1]
CURSOR_256 = 0xffffaf
CSI = re.compile(r'\x1b\[([0-?]*)([ -/]*)([@-~])')


def contrast(a, b):
    def lum(c):
        components=[(c >> shift & 255)/255 for shift in (16,8,0)]
        linear=[s/12.92 if s<=0.04045 else ((s+0.055)/1.055)**2.4 for s in components]
        return sum(x*w for x,w in zip(linear,(0.2126,0.7152,0.0722)))
    x,y=sorted((lum(a),lum(b)))
    return (y+0.05)/(x+0.05)


def indexed_rgb(n):
    if 232 <= n <= 255:
        return (8+10*(n-232))*0x010101
    if 16 <= n < 232:
        n-=16; v=(0,95,135,175,215,255)
        return v[n//36]<<16 | v[(n//6)%6]<<8 | v[n%6]
    raise AssertionError(f'Unexpected user-configurable ANSI index {n}')


class TerminalModel:
    """Only the CSI controls generated by cpymacs, with explicit RGB handling."""
    def __init__(self, *, rgb=True, indexed=True, ansi=True,
                 defaults=(0xffffff,0), ansi_palette=None):
        self.rgb=rgb; self.indexed=indexed; self.ansi=ansi
        self.defaults=defaults
        self.palette=ansi_palette or [0x333333]*16
        self.cells={}; self.row=0; self.col=0
        self.fg,self.bg=defaults
        self.underline=False; self.reverse=False
        self.ansi_indices=[]

    def sgr(self, params):
        p=[int(x) if x else 0 for x in params.split(';')]; i=0
        while i<len(p):
            n=p[i]; i+=1
            if n==0:
                self.fg,self.bg=self.defaults
                self.underline=False; self.reverse=False
            elif n==4:self.underline=True
            elif n==7:self.reverse=True
            elif n in (1,2,5,8):raise AssertionError(f'Unsafe text attribute {n}')
            elif n in (38,48):
                kind=p[i]; i+=1; accepted=False
                if kind==5:
                    index=p[i]; i+=1; self.ansi_indices.append(index)
                    color=indexed_rgb(index) if index>=16 else self.palette[index]
                    accepted=self.indexed and self.ansi
                elif kind==2:
                    r,g,b=p[i:i+3]; i+=3; color=r<<16 | g<<8 | b
                    accepted=self.rgb and self.ansi
                else:raise AssertionError(f'Unknown colour form {kind}')
                if accepted:
                    if n==38:self.fg=color
                    else:self.bg=color
            elif 30<=n<=37 or 40<=n<=47 or 90<=n<=107:
                raise AssertionError('ANSI base palette must not be used')
            else:raise AssertionError(f'Unknown SGR {n}')

    def feed(self, data):
        text=data.decode('utf-8',errors='replace'); i=0
        while i<len(text):
            if text[i]=='\x1b':
                match=CSI.match(text,i)
                if not match:
                    # A final read may end part way through an escape sequence.
                    if len(text)-i<90:return
                    raise AssertionError(f'Unknown terminal sequence: {text[i:i+32]!r}')
                params,_,command=match.groups(); i=match.end()
                if command=='m':self.sgr(params)
                elif command=='H':
                    coords=[int(x) if x else 1 for x in params.split(';')]
                    self.row=coords[0]-1; self.col=(coords[1] if len(coords)>1 else 1)-1
                elif command=='J':self.cells.clear()
                elif command in 'hl':pass
                else:raise AssertionError(f'Unexpected CSI {command}')
                continue
            ch=text[i]; i+=1
            if ch<' ':continue
            fg,bg=(self.bg,self.fg) if self.reverse else (self.fg,self.bg)
            if unicodedata.combining(ch):
                continue
            width=2 if unicodedata.east_asian_width(ch) in ('W','F') else 1
            self.cells[self.row,self.col]=(ch,fg,bg,self.underline)
            if width==2:self.cells[self.row,self.col+1]=('',fg,bg,self.underline)
            self.col+=width
        return self

    def row_text(self,row):
        return ''.join(self.cells.get((row,c),(' ',))[0] for c in range(80))


class LegacyPuttyModel(TerminalModel):
    """Relevant SGR semantics from PuTTY 0.70, not a running PuTTY binary.

    Reference: https://sources.debian.org/src/putty/0.70-6/terminal.c/
    The SGR switch handles 38/48 only when followed by 5 and an index. For
    38;2 or 48;2 it leaves all later operands in the main attribute loop.
    21/4 enable underline, 25 disables blink, and 31 sets ANSI red.
    """
    def sgr(self, params):
        p=[int(x) if x else 0 for x in params.split(';')]; i=0
        while i<len(p):
            n=p[i]; i+=1
            if n==0:
                self.fg,self.bg=self.defaults
                self.underline=False; self.reverse=False
            elif n in (4,21):self.underline=True
            elif n==24:self.underline=False
            elif n==7:self.reverse=True
            elif n==27:self.reverse=False
            elif n in (38,48):
                if i+1<len(p) and p[i]==5:
                    index=p[i+1]&255; i+=2
                    self.ansi_indices.append(index)
                    color=indexed_rgb(index) if index>=16 else self.palette[index]
                    if self.indexed and self.ansi:
                        if n==38:self.fg=color
                        else:self.bg=color
                # For unsupported kinds (notably 2), consume nothing else.
            elif 30<=n<=37 or 90<=n<=97:
                if self.ansi:self.fg=self.palette[n-30 if n<90 else n-90+8]
            elif 40<=n<=47 or 100<=n<=107:
                if self.ansi:self.bg=self.palette[n-40 if n<100 else n-100+8]
            elif n==39:self.fg=self.defaults[0]
            elif n==49:self.bg=self.defaults[1]
            # Unneeded attributes/unknown values do not alter these test cells.


class Session:
    def __init__(self, directory, extra=(), env=None, target=None, profile=True):
        self.master,self.slave=pty.openpty()
        fcntl.ioctl(self.slave,termios.TIOCSWINSZ,struct.pack('HHHH',24,80,0,0))
        self.before=termios.tcgetattr(self.slave)
        self.output=bytearray(); self.errors=tempfile.TemporaryFile()
        environment=dict(os.environ,TERM='xterm',LC_ALL='C.UTF-8')
        for key in ('CPYMACS_TUI_COLORS','CPYMACS_TUI_CURSOR','COLORTERM'):
            environment.pop(key,None)
        environment.update(env or {})
        args=[BINARY,'--nox',*extra]
        if '--connect' not in extra:
            args+=['--no-user-config']
            if profile:args+=['--config',str(ROOT/'examples/dotemacs.py')]
        if target:args.append(str(target))
        self.process=subprocess.Popen(args,stdin=self.slave,stdout=self.slave,
                                      stderr=self.errors,env=environment)
        self.drain_until(lambda: b'\x1b[?2004h' in self.output and b'\x1b[24;1H' in self.output)
        self.pump(0.06)

    def pump(self, seconds=0.12):
        end=time.monotonic()+seconds
        while time.monotonic()<end:
            if select.select([self.master],[],[],max(0,min(0.025,end-time.monotonic())))[0]:
                self.output.extend(os.read(self.master,262144))

    def drain_until(self,predicate,timeout=8):
        end=time.monotonic()+timeout
        while not predicate():
            self.pump(0.03)
            if time.monotonic()>end or self.process.poll() is not None:
                self.errors.seek(0)
                raise AssertionError(f'Terminal not ready: {self.errors.read()!r}')

    def keys(self,text):
        os.write(self.master,text)
        self.pump(0.2)

    def close(self):
        if self.process.poll() is None:self.process.send_signal(signal.SIGTERM)
        end=time.monotonic()+6
        while self.process.poll() is None and time.monotonic()<end:self.pump(0.03)
        if self.process.poll() is None:self.process.kill()
        self.process.wait(timeout=3); self.pump(0.02)
        after=termios.tcgetattr(self.slave)
        os.close(self.master); os.close(self.slave)
        self.errors.seek(0); errors=self.errors.read().decode(errors='replace'); self.errors.close()
        if after!=self.before:raise AssertionError('Terminal attributes not restored')
        if 'AddressSanitizer' in errors or 'runtime error:' in errors:raise AssertionError(errors)
        if b'\x1b[?25h' not in self.output:raise AssertionError('Cursor visibility not restored')
        return self.process.returncode


class TerminalColourTests(unittest.TestCase):
    def setUp(self):
        self.temp=tempfile.TemporaryDirectory(prefix='cpymacs-colour-')
        self.directory=Path(self.temp.name)
        self.target=self.directory/'colors.py'
        self.target.write_text('# Comment must be readable\ndef answer(value=42):\n    return "text"\n')
        self.sessions=[]

    def tearDown(self):
        try:
            for session in self.sessions:session.close()
        finally:self.temp.cleanup()

    def session(self,extra=(),env=None,target=True,profile=True):
        s=Session(self.directory,extra,env,self.target if target else None,profile=profile)
        self.sessions.append(s); return s

    def test_auto_paints_same_colors_under_hostile_user_palettes(self):
        s=self.session()
        self.assertIn(b'38;5;',s.output); self.assertNotIn(b'38;2;',s.output)
        self.assertNotIn(b'\x1b]',s.output)
        self.assertIn('# Comment',TerminalModel().feed(bytes(s.output)).row_text(0))
        for rgb,indexed in ((True,True),(False,True)):
            first=None
            for defaults,palette in (((0xffffff,0),[0]*16),
                                     ((0,0xffffff),[0xffffff]*16),
                                     ((0xff00ff,0xff00ff),[0xff00ff]*16)):
                with self.subTest(rgb=rgb,indexed=indexed,defaults=defaults):
                    model=TerminalModel(rgb=rgb,indexed=indexed,defaults=defaults,ansi_palette=palette)
                    model.feed(bytes(s.output))
                    if first is None:first=model.cells
                    else:self.assertEqual(model.cells,first)
                    self.assertEqual(len(model.cells),24*80)
                    for cell in model.cells.values():self.assertGreaterEqual(contrast(cell[1],cell[2]),7.0)
                    self.assertTrue(all(n>=16 for n in model.ansi_indices))

    def test_auto_remains_indexed_despite_truecolor_environment(self):
        for term in ('xterm','putty','putty-256color','screen-256color','tmux-256color',
                     'xterm-direct'):
            for colorterm in ('truecolor','24bit'):
                with self.subTest(term=term,colorterm=colorterm):
                    s=self.session(env={'TERM':term,'COLORTERM':colorterm})
                    self.assertIn(b'38;5;',s.output)
                    self.assertNotIn(b'38;2;',s.output)
                    self.assertNotIn(b'48;2;',s.output)

    def test_plain_text_and_padding_never_underlined(self):
        for policy in ('auto','256','truecolor','mono'):
            for profile in (False,True):
                with self.subTest(policy=policy,profile=profile):
                    s=self.session((f'--tui-colors={policy}',),profile=profile)
                    s.keys(b'\x00\x06\x06\x06')  # Select three characters.
                    model=TerminalModel().feed(bytes(s.output))
                    self.assertFalse(any(cell[3] for cell in model.cells.values()))
                    s.keys(b'\x07\x1bx')  # Cancel region; show minibuffer.
                    model=TerminalModel().feed(bytes(s.output))
                    self.assertFalse(any(cell[3] for cell in model.cells.values()))

    def test_legacy_parser_reproduces_old_red_underlined_default(self):
        # This fixture is output captured from the actual 0.1.1 executable,
        # with no user config and the default theme, matching the report.
        raw=(ROOT/'tests/fixtures/0.1.1-default.ansi').read_bytes()
        palette=[0x333333]*16; palette[1]=0xbb0000
        model=LegacyPuttyModel(ansi_palette=palette).feed(raw)
        ordinary=[cell for (r,c),cell in model.cells.items() if r<22 and r!=16]
        self.assertGreater(len(ordinary),1000)
        self.assertTrue(all(cell[1]==0xbb0000 and cell[3] for cell in ordinary))
        self.assertIn('import',model.row_text(5))
        self.assertIn(b'48;2;21;25;31m',raw)

    def test_legacy_parser_no_red_lines_with_both_themes(self):
        for profile in (False,True):
            s=self.session(profile=profile)
            s.keys(b'\x06')  # Expose the first token instead of the cursor.
            first=None
            for defaults,color in (((0xffffff,0),0),((0,0xffffff),0xffffff),
                                   ((0xff00ff,0xff00ff),0xff00ff)):
                with self.subTest(profile=profile,defaults=defaults):
                    modern=TerminalModel(defaults=defaults,ansi_palette=[color]*16).feed(bytes(s.output))
                    old=LegacyPuttyModel(defaults=defaults,ansi_palette=[color]*16).feed(bytes(s.output))
                    self.assertEqual(old.cells,modern.cells)
                    self.assertFalse(any(cell[3] for cell in old.cells.values()))
                    if first is None:first=old.cells
                    else:self.assertEqual(old.cells,first)
                    for cell in old.cells.values():self.assertGreaterEqual(contrast(cell[1],cell[2]),7.0)
                    # Keywords, numbers, strings and comments retain distinct colours.
                    foregrounds={cell[1] for (r,c),cell in old.cells.items() if r<3 and cell[0]!=' '}
                    self.assertGreaterEqual(len(foregrounds),5)

    def test_existing_underline_state_is_reset(self):
        s=self.session()
        for factory in (TerminalModel,LegacyPuttyModel):
            model=factory(); model.underline=True; model.reverse=True
            model.feed(bytes(s.output))
            self.assertFalse(any(cell[3] for cell in model.cells.values()))

    def test_forced_256_and_rgb_only(self):
        for policy,expected,absent in (('256',b'38;5;',b'38;2;'),('truecolor',b'38;2;',b'38;5;')):
            with self.subTest(policy=policy):
                s=self.session((f'--tui-colors={policy}',))
                self.assertIn(expected,s.output); self.assertNotIn(absent,s.output)

    def test_monochrome_and_unknown_term_do_not_send_color(self):
        for extra,env in ((('--tui-colors','mono'),{}),((),{'TERM':'vt100'}),
                          ((),{'CPYMACS_TUI_COLORS':'mono'})):
            with self.subTest(extra=extra,env=env):
                s=self.session(extra,env)
                self.assertNotIn(b'38;',s.output); self.assertNotIn(b'48;',s.output)
                model=TerminalModel(defaults=(0,0xffffff)).feed(bytes(s.output))
                self.assertIn('Comment',model.row_text(0))
                for cell in model.cells.values():self.assertGreaterEqual(contrast(cell[1],cell[2]),7.0)

    def test_selection_and_cursor_survive_all_color_controls_disabled(self):
        s=self.session(); s.keys(b'\x00\x06\x06\x06')
        # Defaults still have to be legible: no app can fix foreground==background
        # if the client rejects every colour change.
        model=TerminalModel(ansi=False,defaults=(0,0xffffff)).feed(bytes(s.output))
        self.assertFalse(any(cell[3] for cell in model.cells.values()))
        self.assertEqual(model.cells[(0,0)][1:3],(0xffffff,0))
        self.assertEqual(model.cells[(0,4)][1:3],(0,0xffffff))
        self.assertIn('Comment',model.row_text(0))
        for cell in model.cells.values():self.assertGreaterEqual(contrast(cell[1],cell[2]),7.0)

    def test_block_cursor_moves_without_ghost_and_prompt_is_visible(self):
        s=self.session()
        before=TerminalModel().feed(bytes(s.output))
        cursor_before=before.cells[(0,0)]
        self.assertEqual(cursor_before[2],CURSOR_256)
        s.keys(b'\x06')
        after=TerminalModel().feed(bytes(s.output))
        self.assertNotEqual(after.cells[(0,0)][2],CURSOR_256)
        self.assertEqual(after.cells[(0,1)][2],CURSOR_256)
        s.keys(b'\x1bx')
        prompt=TerminalModel().feed(bytes(s.output))
        self.assertIn('M-x',prompt.row_text(23))
        self.assertTrue(any(cell[2]==CURSOR_256 for (r,c),cell in prompt.cells.items() if r==23))
        self.assertFalse(any(cell[2]==CURSOR_256 for (r,c),cell in prompt.cells.items() if r<23))

    def test_terminal_cursor_and_option_precedence(self):
        s=self.session(('--tui-colors','256','--tui-cursor=terminal'),
                       {'CPYMACS_TUI_COLORS':'mono','CPYMACS_TUI_CURSOR':'block'})
        self.assertIn(b'38;5;',s.output); self.assertNotIn(b'38;2;',s.output)
        self.assertIn(b'\x1b[?25h',s.output)
        self.assertFalse(any(cell[2]==CURSOR_256 for cell in TerminalModel().feed(bytes(s.output)).cells.values()))

    def test_wide_character_cursor_and_split_panes(self):
        self.target.write_text("\u65e5\u672c\u8a9e\n")
        s=self.session()
        model=TerminalModel().feed(bytes(s.output))
        self.assertEqual(model.cells[(0,0)][2],CURSOR_256)
        self.assertEqual(model.cells[(0,1)][2],CURSOR_256)
        s.keys(b'\x06')
        model=TerminalModel().feed(bytes(s.output))
        self.assertNotEqual(model.cells[(0,0)][2],CURSOR_256)
        self.assertEqual(model.cells[(0,2)][2],CURSOR_256)
        self.assertEqual(model.cells[(0,3)][2],CURSOR_256)
        s.keys(b'\x18' + b'3' + b'\x18o')
        model=TerminalModel().feed(bytes(s.output))
        self.assertEqual(model.cells[(0,42)][2],CURSOR_256)
        self.assertNotEqual(model.cells[(0,2)][2],CURSOR_256)
        self.assertEqual(len(model.cells),24*80)

    def test_terminal_options_reject_typos_without_backend(self):
        for args in (['--nox','--tui-colors=nope'],['--nox','--tui-cursor=nope'],
                     ['--tui-colors'],['--tui-cursor'],['--batch','--tui-colors=256']):
            result=subprocess.run([BINARY,*args],capture_output=True,timeout=3)
            self.assertEqual(result.returncode,2,result)
            self.assertIn(b'cpymacs:',result.stderr)
            self.assertFalse(result.stdout)

    def test_tui_colors_implies_nox_even_with_display_set(self):
        master,slave=pty.openpty()
        try:
            env=dict(os.environ,DISPLAY='invalid:73',TERM='xterm')
            p=subprocess.Popen([BINARY,'--tui-colors=mono','--no-user-config'],stdin=slave,stdout=slave,
                               stderr=subprocess.PIPE,env=env)
            output=b''; deadline=time.monotonic()+5
            while b'\x1b[?2004h' not in output and time.monotonic()<deadline:
                if select.select([master],[],[],0.05)[0]:output+=os.read(master,65536)
            self.assertIn(b'\x1b[?2004h',output)
            os.write(master,b'\x18\x03')
            deadline=time.monotonic()+5
            while p.poll() is None and time.monotonic()<deadline:
                if select.select([master],[],[],0.05)[0]:output+=os.read(master,65536)
            if p.poll() is None:p.kill()
            self.assertEqual(p.wait(timeout=3),0)
            self.assertNotIn(b'X11',p.stderr.read()); p.stderr.close()
        finally:os.close(master);os.close(slave)

    def test_resize_repaints_background_and_preserves_editing(self):
        s=self.session()
        fcntl.ioctl(s.slave,termios.TIOCSWINSZ,struct.pack('HHHH',30,100,0,0))
        s.drain_until(lambda:b'\x1b[30;1H' in s.output)
        model=TerminalModel(defaults=(0xff00ff,0xff00ff)).feed(bytes(s.output))
        self.assertEqual(len(model.cells),30*100)
        for cell in model.cells.values():self.assertGreaterEqual(contrast(cell[1],cell[2]),7.0)
        s.keys(b'\x1b[200~inserted\x1b[201~\x18\x13')
        s.drain_until(lambda:self.target.read_text().startswith('inserted'))

    def test_connected_frontend_does_not_change_backend_theme(self):
        sockpath=self.directory/'editor.sock'
        server=subprocess.Popen([BINARY,'--server',str(sockpath),'--no-user-config','--config',
                                 str(ROOT/'examples/dotemacs.py'),str(self.target)],stderr=subprocess.PIPE)
        client=socket.socket(socket.AF_UNIX); client.settimeout(5)
        try:
            end=time.monotonic()+5
            while not sockpath.exists():
                if time.monotonic()>end:raise AssertionError('Socket not ready')
                time.sleep(0.02)
            client.connect(str(sockpath))
            with client.makefile('rwb') as stream:
                def snapshot():
                    stream.write(b'{"op":"snapshot"}\n'); stream.flush()
                    return json.loads(stream.readline())['state']
                before=snapshot()
                s=self.session(('--connect',str(sockpath),'--tui-colors=256'),target=False)
                after=snapshot()
                self.assertEqual(before['colors'],after['colors'])
                self.assertEqual(before['theme'],after['theme'])
                self.assertIn(b'38;5;',s.output)
                self.assertEqual(s.close(),0); self.sessions.remove(s)
                self.assertEqual(snapshot()['colors'],before['colors'])
        finally:
            client.close(); server.terminate(); server.wait(timeout=5); server.stderr.close()


if __name__=='__main__':unittest.main(verbosity=2)
